#!/usr/bin/env python3
"""Record the actual Python/PyTorch/CUDA environment without credentials."""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


def _command(command: list[str]) -> tuple[int, str]:
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=8)
        return result.returncode, (result.stdout or result.stderr).strip()
    except (OSError, subprocess.SubprocessError) as exc:
        return 127, repr(exc)


def collect() -> dict:
    torch_info: dict = {"installed": False}
    try:
        import torch

        torch_info = {
            "installed": True,
            "version": torch.__version__,
            "cuda_available": bool(torch.cuda.is_available()),
            "compiled_cuda": torch.version.cuda,
            "device_count": int(torch.cuda.device_count()),
            "devices": [torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())],
        }
    except ImportError:
        pass
    nvidia_smi = shutil.which("nvidia-smi")
    nvidia = {"available": False, "devices": []}
    if nvidia_smi:
        code, output = _command([nvidia_smi, "--query-gpu=name,driver_version,memory.total,compute_cap", "--format=csv,noheader"])
        if code == 0:
            for line in output.splitlines():
                fields = [field.strip() for field in line.split(",")]
                if len(fields) == 4:
                    nvidia["devices"].append(dict(zip(["name", "driver", "memory", "compute_capability"], fields)))
            nvidia["available"] = bool(nvidia["devices"])
    return {
        "schema_version": 1,
        "operating_system": {"system": platform.system(), "release": platform.release(), "version": platform.version(), "machine": platform.machine()},
        "python": {"version": platform.python_version(), "executable_role": "interpreter running this script"},
        "torch": torch_info,
        "nvidia": nvidia,
        "cuda_toolkit": {"nvcc_found": bool(shutil.which("nvcc")), "nvcc_version": _command([shutil.which("nvcc") or "nvcc", "--version"])[1].splitlines()[-1] if shutil.which("nvcc") else None},
        "compiler": {"cl": bool(shutil.which("cl")), "gxx": bool(shutil.which("g++")), "gcc": bool(shutil.which("gcc"))},
        "hardware_mode": "cuda" if nvidia["available"] and shutil.which("nvcc") else "cpu_only",
        "nsight": {"ncu": bool(shutil.which("ncu")), "nsys": bool(shutil.which("nsys"))},
    }


def markdown(data: dict) -> str:
    torch_info = data["torch"]
    lines = [
        "# Environment Audit",
        "",
        "Generated by `scripts/detect_environment.py`.",
        "",
        f"- Mode: `{data['hardware_mode']}`",
        f"- OS: {data['operating_system']['system']} {data['operating_system']['release']}",
        f"- Python: `{data['python']['version']}`",
        f"- PyTorch: `{torch_info.get('version', 'not installed')}`",
        f"- `torch.cuda.is_available()`: `{torch_info.get('cuda_available', False)}`",
        f"- CUDA Toolkit (`nvcc`): `{data['cuda_toolkit']['nvcc_version'] or 'not found'}`",
        f"- NVIDIA devices: `{len(data['nvidia']['devices'])}`",
        f"- Nsight Compute: `{data['nsight']['ncu']}`",
        f"- Nsight Systems: `{data['nsight']['nsys']}`",
        "",
    ]
    if data["hardware_mode"] != "cuda":
        lines.append("CUDA benchmark status: `NOT BENCHMARKED ON CURRENT HARDWARE`.")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=Path("results"))
    args = parser.parse_args()
    data = collect()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "environment.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    (args.output_dir / "environment.md").write_text(markdown(data), encoding="utf-8")
    print(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()

